### Get All Categories
GET http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json

### Create New Category
POST http://localhost:3000/api/categories
X-API-Key: RAHASIA
Accept: application/json
Content-Type: application/json

{
  "name": "Aweawe"
}

### Get Category by ID
GET  http://localhost:3000/api/categories/100
Content-Type: application/json

### Update Category ID
PUT http://localhost:3000/api/categories/1
Accept: application/json
Content-Type: application/json

{
  "name": ""
}

### Delete Category by ID
DELETE  http://localhost:3000/api/categories/10
Content-Type: application/json


